FROM python:3.8

MAINTAINER Satyanjal Prakash version: 0.1

RUN mkdir -p /home/application/logs

COPY django_app /home/application/

RUN rm -rf /home/application/django_app/application.conf

RUN pip3.6 install django-cors-headers
RUN pip3.6 install -r /home/application/coding_course/requirements.txt
env LOGIN_APP_CONFIG_FILE=/home/application/django_app/application.conf
WORKDIR /home/application/django_app/

EXPOSE 8000
CMD ["gunicorn", "-b", "0.0.0.0:8118", "-w", "5", "login_app.wsgi"]


